name: operation_result
description: The Result that allows to specify a list of expected errors.
version: 1.0.1

homepage: https://github.com/vkubiv/operation_result
repository: https://github.com/vkubiv/operation_result
issue_tracker: https://github.com/vkubiv/operation_result/issues

environment:
  sdk: ">=3.0.0 <4.0.0"


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
